### ISSUE TITLE
docker-composer.yml has an error

### ISSUE THREAD

**Issue by quteibah** [n8n-io/n8n-hosting#12]
Hi. please remove or review this part of the .yml file in line 38:

`      - 'traefik.http.routers.n8n.rule=PathPrefix(`/${SUBFOLDER}{regex:$$|/.*}`)'`

I don't know why but it gives 404 with that regex but when removed, like this:

`      - 'traefik.http.routers.n8n.rule=PathPrefix(`/${SUBFOLDER}`)'`

works like a charm.

**Comment by gwbischof** [comment]
I hit is error also.

I think the port mapping for n8n should be updated also like this.
The port mapping as it currently is will map the 5678 port on your host to the 5678 port in the container, thereby bypassing the Traefik proxy.
```
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.89.2
    expose:
      - "5678"
```
